name: Build and Deploy API code

on: [push, pull_request]

jobs:
  job_api_1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: starting agik works
        run: echo "Started running agik API code"
      - name: Install python version 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all the dependencies
        run:  pip install -r requirements.txt .