name: Build and Deploy API code

on: [push, pull_request]

jobs:
  job_api_1:
    env:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 3306
      DATABASE_PASSWORD: root
      DATABASE_NAME: api_dev
      DATABASE_USERNAME: root
      SECRET_KEY: nN3ruYLMhmoph83XPTCvVBBQBHmgp07I
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: starting agik works
        run: echo "Started running agik API code"
      - name: Install python version 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all the dependencies
        run: pip install -r requirements.txt
      - name: run API Tests
        run:
          pip install pytest
          pytest
